package com.tvm.tvm.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tvm.tvm.bean.PriceList;
import com.tvm.tvm.bean.User;

import com.tvm.tvm.bean.dao.PriceListDao;
import com.tvm.tvm.bean.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig priceListDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PriceListDao priceListDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        priceListDaoConfig = daoConfigMap.get(PriceListDao.class).clone();
        priceListDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        priceListDao = new PriceListDao(priceListDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PriceList.class, priceListDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        priceListDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PriceListDao getPriceListDao() {
        return priceListDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
