package com.tvm.tvm.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tvm.tvm.bean.TicketSummary;
import com.tvm.tvm.bean.User;
import com.tvm.tvm.bean.PaymentRecord;
import com.tvm.tvm.bean.Price;

import com.tvm.tvm.bean.dao.TicketSummaryDao;
import com.tvm.tvm.bean.dao.UserDao;
import com.tvm.tvm.bean.dao.PaymentRecordDao;
import com.tvm.tvm.bean.dao.PriceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ticketSummaryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig paymentRecordDaoConfig;
    private final DaoConfig priceDaoConfig;

    private final TicketSummaryDao ticketSummaryDao;
    private final UserDao userDao;
    private final PaymentRecordDao paymentRecordDao;
    private final PriceDao priceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ticketSummaryDaoConfig = daoConfigMap.get(TicketSummaryDao.class).clone();
        ticketSummaryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        paymentRecordDaoConfig = daoConfigMap.get(PaymentRecordDao.class).clone();
        paymentRecordDaoConfig.initIdentityScope(type);

        priceDaoConfig = daoConfigMap.get(PriceDao.class).clone();
        priceDaoConfig.initIdentityScope(type);

        ticketSummaryDao = new TicketSummaryDao(ticketSummaryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        paymentRecordDao = new PaymentRecordDao(paymentRecordDaoConfig, this);
        priceDao = new PriceDao(priceDaoConfig, this);

        registerDao(TicketSummary.class, ticketSummaryDao);
        registerDao(User.class, userDao);
        registerDao(PaymentRecord.class, paymentRecordDao);
        registerDao(Price.class, priceDao);
    }
    
    public void clear() {
        ticketSummaryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        paymentRecordDaoConfig.clearIdentityScope();
        priceDaoConfig.clearIdentityScope();
    }

    public TicketSummaryDao getTicketSummaryDao() {
        return ticketSummaryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PaymentRecordDao getPaymentRecordDao() {
        return paymentRecordDao;
    }

    public PriceDao getPriceDao() {
        return priceDao;
    }

}
