package com.tvm.tvm.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tvm.tvm.bean.BillSetting;
import com.tvm.tvm.bean.PaymentRecord;
import com.tvm.tvm.bean.Price;
import com.tvm.tvm.bean.Setting;
import com.tvm.tvm.bean.TicketSummary;
import com.tvm.tvm.bean.User;

import com.tvm.tvm.bean.dao.BillSettingDao;
import com.tvm.tvm.bean.dao.PaymentRecordDao;
import com.tvm.tvm.bean.dao.PriceDao;
import com.tvm.tvm.bean.dao.SettingDao;
import com.tvm.tvm.bean.dao.TicketSummaryDao;
import com.tvm.tvm.bean.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billSettingDaoConfig;
    private final DaoConfig paymentRecordDaoConfig;
    private final DaoConfig priceDaoConfig;
    private final DaoConfig settingDaoConfig;
    private final DaoConfig ticketSummaryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BillSettingDao billSettingDao;
    private final PaymentRecordDao paymentRecordDao;
    private final PriceDao priceDao;
    private final SettingDao settingDao;
    private final TicketSummaryDao ticketSummaryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billSettingDaoConfig = daoConfigMap.get(BillSettingDao.class).clone();
        billSettingDaoConfig.initIdentityScope(type);

        paymentRecordDaoConfig = daoConfigMap.get(PaymentRecordDao.class).clone();
        paymentRecordDaoConfig.initIdentityScope(type);

        priceDaoConfig = daoConfigMap.get(PriceDao.class).clone();
        priceDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        ticketSummaryDaoConfig = daoConfigMap.get(TicketSummaryDao.class).clone();
        ticketSummaryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        billSettingDao = new BillSettingDao(billSettingDaoConfig, this);
        paymentRecordDao = new PaymentRecordDao(paymentRecordDaoConfig, this);
        priceDao = new PriceDao(priceDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);
        ticketSummaryDao = new TicketSummaryDao(ticketSummaryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BillSetting.class, billSettingDao);
        registerDao(PaymentRecord.class, paymentRecordDao);
        registerDao(Price.class, priceDao);
        registerDao(Setting.class, settingDao);
        registerDao(TicketSummary.class, ticketSummaryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        billSettingDaoConfig.clearIdentityScope();
        paymentRecordDaoConfig.clearIdentityScope();
        priceDaoConfig.clearIdentityScope();
        settingDaoConfig.clearIdentityScope();
        ticketSummaryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BillSettingDao getBillSettingDao() {
        return billSettingDao;
    }

    public PaymentRecordDao getPaymentRecordDao() {
        return paymentRecordDao;
    }

    public PriceDao getPriceDao() {
        return priceDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

    public TicketSummaryDao getTicketSummaryDao() {
        return ticketSummaryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
