/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tvm_tvm_util_device_SerialPortUtil */

#ifndef _Included_com_tvm_tvm_util_device_SerialPortUtil
#define _Included_com_tvm_tvm_util_device_SerialPortUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tvm_tvm_util_device_SerialPortUtil
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_tvm_tvm_util_device_SerialPortUtil_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_tvm_tvm_util_device_SerialPortUtil
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tvm_tvm_util_device_SerialPortUtil_close
  (JNIEnv *, jobject);

/*
 * Class:     com_tvm_tvm_util_device_SerialPortUtil
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tvm_tvm_util_device_SerialPortUtil_getMessageFromJNI
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
